# Site settings
author: Shawanda Davis
title: In Coding Color
header-img: img/home-bg.png
email: shawandadavis93@gmail.com
copyright_name: Shawanda Davis
description: > # this means to ignore newlines until "baseurl:"
  Humor me for a second...who knows, you may just learn something.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ShawandaMD

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
